Isolate the code for SimpleXmlReader parser
ERDDAP/erddap pull request #161
Opened 2024-06-17 16:53 UTC by ayushsingh01042003

# Description

- Some code restructuring and cleanup
- Moving the static functions to the EDStatic Class
- Functions for sending particular emails

2024-06-17 19:52 UTC, ChrisJohnNOAA requested changes
A few small changes, mostly naming.

2024-06-17 19:52 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/erddap/util/EDStatic.java
> +    public static void resetTimeDistributions() {
resetDailyDistributions

This doesn't reset all of the distributions on EDStatic

2024-06-17 19:52 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/erddap/util/EDStatic.java
> +    public static void clearAllTallies() {
clearDailyTallies

2024-06-17 19:52 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/erddap/LoadDatasets.java
> +            EDStatic.suggestAddFillValueCSV.setLength(0);
I believe `EDStatic.suggestAddFillValueCSV` is used as part of the `handleAfva`. I think the call `EDStatic.suggestAddFillValueCSV.setLength(0);` is unrelated to the xml parsing function and so should be in the main run.

2024-06-17 19:52 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/erddap/LoadDatasets.java
> +            String subject = String2.ERROR + " while processing " +
This is minor, but we should move this string definition into the if.

2024-06-18 07:36 UTC, ayushsingh01042003 commented
Does this look good?

2024-06-18 12:37 UTC, ChrisJohnNOAA approved these changes

2024-06-18 15:04 UTC, merged