Load Resources with Guava API
ERDDAP/erddap pull request #200
Opened 2024-09-14 01:22 UTC by SethChampagneNRL

# Description:

Compiling ERDDAP source into a jar file does not work due to the way ERDDAP accesses several static resource files. This change is to move the classpath resources into the main/resources source set, and patch the code to load classpath resources using the Guava Resources API. This fixes some of the assumptions that ERDDAP makes about the `WEB-INF/classes` directory, and allows the ERDDAP source to be bundled into builds as a jar file dependency.

Resource files outside of the classpath remain in place. The code will still use filesystem paths for other directories within WEB-INF (e.g. cptfiles, ref, etc). This change should not impact any existing ERDDAP deployments since all files can remain where they are in the war artifacts.  

## Changes:
+ Remove _classPath_ and _webInfParentDirectory_ static variables from File2
+ References to _webInfParentDirectory_ will all use the variable from EDStatic
+ Change ERDDAP to load classpath resources using Guava Resources utility
+ Continue loading non-classpath resources via file paths relative to WEB-INF directory
+ Move resources to *main* source set following Java standard practice
+ Allows access to resources within jar files, adding support for alternative build DevOps

I wanted to additionally change the File2 WEB-INF directory lookup to use the ServletContext, but this would require changing the way EDStatic is initialized and make it dependent on the Erddap.init() method instead of the Erddap constructor. So WEB-INF parent directory is still located using the classpath of String2.java.

2024-09-16 19:16 UTC, ChrisJohnNOAA requested changes
Many tests are failing when run through maven `mvn test` for me with these changes.

Also, a few questions.

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on src/test/java/gov/noaa/pfel/coastwatch/util/FileVisitorSubdirTests.java
> -        File2.webInfParentDirectory().replace('\\', '/'); // with / separator and / at the end
I believe that replace was needed in some circumstances (on windows machines) to make sure all the file separators were '/'.

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/erddap/Erddap.java
> +import jakarta.servlet.ServletConfig;
I don't see these being used anywhere, remove?

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/coastwatch/hdf/SdsReader.java
> +import com.google.common.io.Resources;
I don't see resources or paths used here, remove?

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/coastwatch/ValidateDataSetProperties.java
> +import com.google.common.io.Resources;
I don't see resources or paths used here, remove?

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/gov/noaa/pfel/coastwatch/util/SSR.java
> -    BufferedReader bufferedReader = File2.getDecompressedBufferedFileReader(fileName, charset);
Here and below, do we definitely never need support for compressed files?

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/com/cohort/util/File2.java
> -  public static void setWebInfParentDirectory() {
This is called from testDataset/Initialization.java and I don't see that file in this.

2024-09-16 19:16 UTC, ChrisJohnNOAA commented on WEB-INF/classes/com/cohort/util/File2.java
> -  private static String webInfParentDirectory; // lazy creation by webInfParentDirectory()
The webInfParentDirectory was set in FIle2 so that tests could initialize it before EDStatic was initialized. The way this is changed, all of the tests that reference EDStatic (directly or indirectly) now error.

2024-09-17 17:56 UTC, SethChampagneNRL commented
I am working on an update to address these issues. The unused imports were from refactoring and I forgot to remove them. I will admit that I am not familiar with Maven so I didn't know how to run the tests, but I have those running now and I will fix the initialization problems. For the SSR, I didn't realize it is also decompressing the stream, but I can update the code to handle that as well. I hope to have all these wrapped up soon. Thanks Chris!

2024-09-17 23:25 UTC, srstsavage commented
Haven't looked closely but I'm getting a single compilation error when running tests after the latest commits:.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project ERDDAP: Compilation failure
[ERROR] /the/path/erddap/src/test/java/gov/noaa/pfel/coastwatch/util/HtmlWidgetsTests.java:[24,28] cannot find symbol
[ERROR]   symbol:   method webInfParentDirectory()
[ERROR]   location: class com.cohort.util.File2
```

2024-09-18 15:33 UTC, ChrisJohnNOAA approved these changes
Thanks for the fixes.

2024-09-18 15:33 UTC, ChrisJohnNOAA commented on WEB-INF/classes/com/cohort/util/XML.java
> +import java.io.*;
Style comment, here and elsewhere, nitpick (especially since the whole code base hasn't been updated for this yet), but the Google style guide we're using says not wildcard imports. https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2024-09-18 15:46 UTC, SethChampagneNRL commented on WEB-INF/classes/com/cohort/util/XML.java
> +import java.io.*;
This was done automatically by Intellij. I will switch my settings so it stops inserting wildcards.

2024-09-18 16:43 UTC, ChrisJohnNOAA approved these changes

2024-09-18 16:44 UTC, SethChampagneNRL commented
I am sorry that my initial pull requests had all of the tests failing but they pass now when I run locally. I brought back the File2 static initialization for tests and `File2.getClassPath()` for some particular parts of the code that were difficult to workaround. 

Two notes:
+ The `git-code-format-maven-plugin` is not working for me. I get a "No valid maven executable found !" message, but this is probably user error on my side. I worked around this by commenting out the plugin in pom.xml when I run maven. 
+ I also had to switch `EDStatic.useSaxParser = false;` in the test Initialization. The new SAX parser seems to cause three of the EDD tests to error. With SAX turned off, I still had only one test error, the `EDDGridTests.testGeotif2()`, and this was due to a 503 error from https://oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/MH/chla/8day.das 

I built the erddap.war using mvn package and I verified it working in tomcat 10. Are there any other changes or documentation updates I should make for this pull request?

2024-09-18 16:51 UTC, ChrisJohnNOAA commented
> I am sorry that my initial pull requests had all of the tests failing but they pass now when I run locally. I brought back the File2 static initialization for tests and `File2.getClassPath()` for some particular parts of the code that were difficult to workaround.
> 
> Two notes:
> 
> * The `git-code-format-maven-plugin` is not working for me. I get a "No valid maven executable found !" message, but this is probably user error on my side. I worked around this by commenting out the plugin in pom.xml when I run maven.
> * I also had to switch `EDStatic.useSaxParser = false;` in the test Initialization. The new SAX parser seems to cause three of the EDD tests to error. With SAX turned off, I still had only one test error, the `EDDGridTests.testGeotif2()`, and this was due to a 503 error from https://oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/MH/chla/8day.das
> 
> I built the erddap.war using mvn package and I verified it working in tomcat 10. Are there any other changes or documentation updates I should make for this pull request?

I'm working on deflaking tests in a separate branch: https://github.com/ChrisJohnNOAA/erddap/tree/ReduceTestFlakiness
I disable the geotif2 test there due to the unreliability of that external dependency. I think the other tests you mention are fixed in that branch.

Given that, I think this is good to go.

2024-09-18 17:03 UTC, merged